import type { Metadata } from "next";
import Link from "next/link";
import { LEGAL_CONTACT_EMAIL, LegalPage, LegalSection } from "@/components/legal/legal-page";
import { GITHUB_URL } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms for using the hosted OpenDiagram service.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service">
      <LegalSection title="Agreement">
        <p>
          These terms apply to the hosted OpenDiagram service at opendiagram.ink (&quot;the
          service&quot;). By creating an account or using the service, you agree to them. If you do
          not agree, do not use the service.
        </p>
      </LegalSection>

      <LegalSection title="The open-source code">
        <p>
          The OpenDiagram source code is licensed separately under the{" "}
          <a href={`${GITHUB_URL}/blob/main/LICENSE`}>AGPL-3.0</a>. These terms cover the hosted
          service only, not your use of the code under that license.
        </p>
      </LegalSection>

      <LegalSection title="Your account">
        <p>
          Give accurate information when you sign up and keep your password safe. You are
          responsible for activity on your account. Tell us at{" "}
          <a href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a> if you think someone
          else has access to it.
        </p>
      </LegalSection>

      <LegalSection title="Your content">
        <p>
          You own what you put into OpenDiagram and the diagrams you create with it. You give us
          permission to store, process, and transmit that content only as needed to run the service
          for you, including sending it to AI model providers as described in our{" "}
          <Link href="/privacy">Privacy Policy</Link>.
        </p>
        <p>Only upload or import content you have the right to use.</p>
      </LegalSection>

      <LegalSection title="AI output">
        <p>
          Diagrams are generated by AI models and can be incomplete or wrong. They are drafts for
          you to review, not verified designs. You are responsible for checking anything you rely
          on.
        </p>
      </LegalSection>

      <LegalSection title="Your own provider keys">
        <p>
          If you connect your own AI provider key, calls made with it are billed to you by that
          provider and are subject to its terms. We are not responsible for charges on your provider
          account.
        </p>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <p>Do not use the service to:</p>
        <ul>
          <li>break the law or infringe anyone&apos;s rights</li>
          <li>upload malware or content you are not allowed to share</li>
          <li>
            probe, overload, or get around the service&apos;s security, rate limits, or plan limits
          </li>
          <li>resell or give others access to your account</li>
        </ul>
      </LegalSection>

      <LegalSection title="Plans and payment">
        <p>
          Paid plans are sold through Dodo Payments, which acts as merchant of record and handles
          checkout, billing, and tax. Subscriptions renew automatically until you cancel, and you
          can cancel at any time; access continues until the end of the paid period. Prices and plan
          limits are shown in the app before you pay and may change with notice before your next
          renewal.
        </p>
      </LegalSection>

      <LegalSection title="Availability and changes">
        <p>
          OpenDiagram is an early product. We may change, add, or remove features, and the service
          may occasionally be unavailable. We will try to give notice of changes that materially
          affect you.
        </p>
      </LegalSection>

      <LegalSection title="Ending your account">
        <p>
          You can stop using the service and ask us to delete your account at any time. We may
          suspend or close accounts that break these terms or put the service or other users at
          risk.
        </p>
      </LegalSection>

      <LegalSection title="Disclaimer and liability">
        <p>
          The service is provided &quot;as is&quot;, without warranties of any kind, to the extent
          the law allows. To the extent the law allows, OpenDiagram is not liable for indirect or
          consequential losses, and our total liability for any claim is limited to the amount you
          paid us in the 12 months before the claim.
        </p>
      </LegalSection>

      <LegalSection title="Changes to these terms">
        <p>
          If we update these terms, we will change the date above and, for significant changes, let
          you know by email or in the app. Continuing to use the service after that means you accept
          the new terms.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          Questions about these terms:{" "}
          <a href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a>, or open an issue on{" "}
          <a href={`${GITHUB_URL}/issues`}>GitHub</a>.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
